/*
 * main_viernes.c
 *
 *  Created on: May 15, 2026
 *      Author: lucas
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
 // #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

// Definicion de variables

uint8_t dummy_8bit = 0;
uint16_t dummy_16bit = 0;
uint32_t dummy_32bit = 0;
uint16_t dummy_16bit_dec = 0;
uint16_t dummy_16bit_hex = 0;
uint16_t dummy_16bit_bin = 0;
uint8_t overflow_demo = 0;


// Funcion main...
int main(void)
{

	dummy_8bit = 123;
	dummy_16bit = 4986;
	dummy_32bit = 123456789;

	dummy_16bit_dec = 32;
	dummy_16bit_hex = 0x20;
	dummy_16bit_bin = 0b100000;

	// cargando el valor xxxx en la variable yyyy
	dummy_16bit_bin = dummy_16bit_bin << 4; //prediccion: 1000000000
	dummy_16bit_bin = dummy_16bit_bin >> 5; //prediction: 10000

	// exponiendo el caso de un overflow
	dummy_8bit = 255;
	dummy_16bit = 255;
	dummy_32bit = 255;

	//incremento el valor de la variable dummy_8bit en 1 y la carga en la variable overflow_demo
	overflow_demo = dummy_8bit + 1; //prediction: 0b0
	overflow_demo = overflow_demo +1; //prediction: 0b1

	overflow_demo = 735; //prediction: 223


    /* Loop forever */
	while(1){

	}
	return 0;
}

