/*
 * main_viernes.c
 *
 *  Created on: May 15, 2026
 *      Author: lucas
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
 // #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

// Definicion de variables

uint8_t dummy_8bit = 0;
uint16_t dummy_16bit = 0;
uint32_t dummy_32bit = 0;
uint16_t dummy_16bit_dec = 0;
uint16_t dummy_16bit_hex = 0;
uint16_t dummy_16bit_bin = 0;
uint8_t overflow_demo = 0;


// Funcion main...
int main(void)
{

//	dummy_8bit = 123;
//	dummy_16bit = 4986;
//	dummy_32bit = 123456789;
//
//	dummy_16bit_dec = 32;
//	dummy_16bit_hex = 0x20;
//	dummy_16bit_bin = 0b100000;
//
//	// cargando el valor xxxx en la variable yyyy
//	dummy_16bit_bin = dummy_16bit_bin << 4; //prediccion: 1000000000
//	dummy_16bit_bin = dummy_16bit_bin >> 5; //prediction: 10000
//
//	// exponiendo el caso de un overflow
//	dummy_8bit = 255;
//	dummy_16bit = 255;
//	dummy_32bit = 255;
//
//	//incremento el valor de la variable dummy_8bit en 1 y la carga en la variable overflow_demo
//	overflow_demo = dummy_8bit + 1; //prediction: 0b0
//	overflow_demo = overflow_demo +1; //prediction: 0b1
//
//	overflow_demo = 735; //prediction: 223

	//* SEMANA 00 *//

//	int8_t my_variable = 0;
//	uint8_t dec = 0;
//	uint8_t hex = 0;
//	uint8_t bin = 0;
//	uint8_t a = 0;
//	uint16_t b = 0;
//	uint32_t c = 0;
//	uint8_t d = 0;
//	uint8_t e = 0;
//	uint8_t aa = 0;
//	int8_t bb = 0;
//	int8_t cc = 0;
//	int8_t x = 0;
//	uint8_t y = 0;
//	uint8_t result = 0;
//
//	//Ejercicio 01
//	my_variable = 42; // verificamos la variable en el variable inspector
//
//	//Ejercicio 02
//	dec = 65;
//	hex = 0x41;
//	bin = 0b01000001;
//
//	/*
//	 * Luego de comprobar con el depurador y el variable inspector, las 3 tienen
//	 * el mismo patron de 8 bits 01000001, lo que significa que tienen el mismo valor
//	 * pero escrito en un sistema numerico diferente (decimal, hexadecimal, binario).
//	 *
//	 * Se pueden mostrar de diferentes formas simplemente por comodidad para la tarea
//	 * que se este realizando, en nuestro caso, nos es mas util en binarip
//	 */
//
//	//Ejercicio 03
//	a = 255;
//	b = 255;
//	c = 255;
//	d = 256;
//	e = 257;
//
//	/*
//	 * Las variables a, b y c guardan el valor esperado (255), pero la variable d almacena 0,
//	 * esto debido a que d es una variable de 8 bits, y por tanto, solo puede almacenar valores
//	 * entre 0 y 255. Por lo que al exceder el limite se reinicia y su valor es 0. Similarmetente,
//	 * con la variable e pasa lo mismo, solo que ahora al 'pasarse' por 2, el valor aumenta en uno
//	 */
//
//	//Ejercicio 04
//	aa = 200; // va a almacenar el 200
//	bb = 200; // no va almacenar el 200 porque va desde -128 a 127 (por ser int con signo)
//	cc = -1;  // si almacena el -1
//
//	/*
//	 * bb no almacena el 200, en su lugar almacena -56, ya que su valor en binario es 11001000 se representa
//	 * como -56 en complemtento a 2 (tomar el signo dependiendo del bit mas significativo, invertir el numero, sumar 1)
//	 *
//	 * cc almacena correctamente el -1, al visualizarlo en hexadecimal se observa 0xFF. El complemento a 2 de un nuemro
//	 * negativo se halla tomando el valor positivo, luego se invierten los bits y se le suma 1, por lo que -1 en binario
//	 * es 11111111, como en hexadecimal F corresponde a cuatro 1 (F=1111) por eso es que -1=0xFF
//	 */
//
//
//
//	//Ejercicio 05
//	x = 127; // va a almacenar el 127
//	x = x + 1; // se va a desbordar y se va a reiniciar, como es int, no va a ser 0 sino -128
//
//	y = 255; // va a almacenar el 255
//	y = y + 1;  // se va a desbordar y se va a reiniciar, como es unsigned va a ser 0
//
//	int8_t aaa = INT8_MAX;
//	int8_t bbb = INT8_MIN;
//	uint8_t ccc = UINT8_MAX;
//	uint16_t ddd = UINT16_MAX;
//
//	/*
//	 * Ocurrio tal y como se habia predicho. Por otro lado, las constantes stdint.h permiten
//	 * conocer los limites de cada tipo de variable
//	 */
//
//	//Ejercicio 06
//	result = 0x0F + 0x01; // no deberia haber overflow
//	result = 0xFF + 0x01; // se deberia debordar ya que la F corresponde a 1111 y por tanto FF corresponde a 11111111
//	result = 0xA0 + 0x5F; // no tengo idea
//	result = 0xA0 + 0x60; // no tengo idea
//
//	/*
//	 * Estuve bien en las dos primeras. Para las dos ultimas, debo repasar mas los numeros en hexadeciaml, aun
//	 * me cuesta identificar valores como 0xA0 o 0x5F, pero la logica de que para 8 bits el rango es de 0x00 a 0xFF
//	 * esta bien
//	 */
//
//
//	//Ejercicio 07
//	x = 0x01;   // 00000001
//	x = 0x02;   // 00000010
//	x = 0x04;   // 00000100
//	x = 0x08;   // 00001000
//	x = 0x10;   // 00010000
//	x = 0x20;   // 00100000
//	x = 0x40;   // 01000000
//	x = 0x80;   // 10000000
//
//	/*
//	 * Cada valor va siendo el doble del anterior, esto pues mover un bit a la izquierda equivale a multiplicar por 2.
//	 *
//	 * Este paron tiene el coomportamioento de un registro shift, que nos permite mover bit por bit, el equivalente a ese mismo
//	 * patron seria un shift hacia la izquierda
//	 */
//
//
//	//Ejercicio 07
//	uint8_t a_08 = 5;
//	uint8_t b_08 = 0;
//	uint8_t c_08 = 255;
//	uint8_t r1 = !a_08; // como ! es el operador NOT logico, si el valor es 0 nos devuelve 1 y si es distinto de 0 devuelve 0, por tanto devuelve 0
//	uint8_t r2 = !b_08; // como b_08 es 0, devuelve 1
//	uint8_t r3 = !c_08; // como c_08 es 255, devuelve 0
//	uint8_t r4 = ~c_08; // como ~ es el operador NOt pero bit a bit, este va a invertir cada bit del numero, como 255 es 11111111 entonces va a devolver 00000000
//	uint8_t r5 = ~a_08; // como a_08 es 5, su representacion en binario es 00000101 y por tanto nos devuelve 11111010 que es 250
//
//	/*
//	 * La negacion logica ! es el valor de verdad de una 'proposicion'pero invertido, es decir, si la la 'proposicion' es verdadera(1) nos devuelve un falso (0)
//	 * y si por el contrario la proposicion es falsa(0) nos devuelve un verdadero(1)
//	 *
//	 * Por otro lado, ~ es la negacion bit a bit, esta invierte cada bit del numero, si era 1 lo pasa a 0 y viceversa
//	 *
//	 * DISCLAIMER: Tecnicamente en programacion verdadero y falso son diferentes a 1 y 0, pero fue la manera que se me ocurrio para explicarlo
//	 * y que se entienda la idea
//	 */
//
//
//	//* SEMANA 01 *//
//
//	//Ejercicio 1.1
//	uint8_t a = 17;
//	uint8_t b = 5;
//
//	uint8_t div_result = a / b; // va a dar 3
//	uint8_t mod_result = a % b; // va a dar 2
//	uint8_t mul_result = a * b; // va a dar 85
//
//	/*
//	 * En C la division entre enteros devuelve un entero, es decir, descarta la parte decimal sin redondear
//	 * La operacion % corresponde al modulo, la cual devuelve el residuo de la division
//	 * La operacion * es una multiplicacion
//	 */
//
//	//Ejercicio 1.2
//	uint8_t x = 200;
//	uint8_t y = 100;
//	uint8_t sum = x + y; // se va adesbordar y sera 44
//
//	/*
//	 * En un sistema rela podria ocurrir por ejemplo, que si se debe a ctivar una alarma
//	 * alcanzado un cierto valor, si no se tienen en cuenta los tamanos de las variables, podria nunca activarse
//	 * la alarma, haciendo que el sistema interprete el valor como seguro y cause un desastre
//	 */
//
//
//
//
//
//	//Ejercicio 1.3
//	uint8_t val = 3; // en bianrio es 00000011
//
//	uint8_t left1 = val << 1; // el resultado sera 00000110
//	uint8_t left2 = val << 2; // sera 00001100
//	uint8_t left3 = val << 3; // sera 00011000
//	uint8_t right1 = val >> 1;// sera 00000001
//
//	// caso limite
//	uint8_t edge = 0b10000000;
//	uint8_t result = edge << 1; // sera 00000000
//
//	/*
//	 * Como edege solo tiene 8 bits, al hacer un shift hacia la izuierda es como si estuvieramos haciendolo de 9 bits, pero como solo caben 8,
//	 * la memoria descarta ese 9no bit y solo almacena los 8 ceros
//	 */
//
//	//Ejercicio 1.4
//	uint8_t a = 5;   // valor distinto de cero
//	uint8_t b = 0;   // valor cero
//	uint8_t c = 5;   // para comparación
//	uint8_t result = 0;
//
//	// Prueba de valor no cero
//	if (a){
//		result = 1;
//	}
//
//	// Prueba de valor cero con if-else
//	if (b){
//		result = 2;
//	}
//	else{
//		result = 3;
//	}
//
//	// Comparación de igualdad
//	if (a == c)
//	{
//		result = 4;
//	}

	/*
	 * El primer if evalua una variable que es distinta de 0, por lo que la condicion es verdadera
	 * y por tanto, result cambia a 1
	 *
	 * El if-else usa una variable igual a cero por lo que la condicion es falsa y pasa a ejecutar el else,
	 * cambiando a result = 3
	 *
	 * Finalmente, en la comparacion de igualdad, resulta verdadera ya que compara los valores de a y c, como son iguales,
	 * entonces cambia result = 4
	 *
	 * Concluimos que el unico valor considerado como falso es 0, por lo que cualquier otro valor distinto de cero se interpreta
	 * como verdadero (incluyendo negativos)
	 */



	//Ejercicio 1.5
//	uint8_t counter = 0;
//
//	    for(int i = 0; i < 10; i++){ // empezara en 0 y aumentara de 1 en 1 hasta 1<10
//	        counter++;
//	    }

//	uint8_t counter = 0;
//
//	for(int i = 0; i < 10; i += 2){ // empezara en 0 y contara de 2 en 2 hasta i<10
//	    counter++;
//	}

//	uint8_t counter = 0;
//
//	for(int i = 10; i > 0; i--){ // empezara en 10 y disminuira de 1 en 1 hasta i>0
//	    counter++;
//	}

//	uint8_t counter = 0;
//
//	for(int i = 0; i < 5; i++){ // empezara en 0 y contara de 1 en 1 hasta 4
//	    counter++;
//	}

	//Ejercicio 1.6

//		uint8_t sum = 0;
//		uint8_t i = 1;

//		while(i <= 10){ // sumara todos los numeros desde 1 hasta 10
//			sum = sum + i; // esperamos 1+2+3+4+5+6+7+8+9+10 = 55
//			i++;
//		}

//		uint16_t sum = 0;
//		uint8_t i = 1;
//
//		while(i <= 100){ // sumara todos los numeros desde 1 hasta 100
//			sum = sum + i; // esperamos 1+2+3+...+100 = 5050
//			i++;
//		}


	//Ejercicio 1.7

//		uint8_t result1 = 0;
//		uint8_t x = 0;
//
//		while(x > 0){ // la condicion es falsa desde el inicio
//			result1 = 42;
//		}// se espera que result1 permanezca en 0 porque el while primero verifica la condicion y nunca entra al bucle


//		uint8_t result2 = 0;
//		uint8_t y = 0;
//
//		do{
//			result2 = 42;
//		}while(y > 0); // la condicion tambien es falsa
//
//		 //se espera que result2 sea 42 porque el do-while ejecuta el bloque al menos una vez

	/*
	 * Como en el primer xaso el bucle while usa una condicion que es falsa desde el inicio
	 * y se evalua la condicion antrs de ejecutar ese bloqque de codigo, el contenido en ese codigo no se ejecuta
	 * y por tanto la variable permanece en 0
	 *
	 * Por otra parte, en el bucle do-while utilizamos la misma condicion falsa, pero el bloque se ejecuta
	 * antes de evaluar esta condicion, es por  esto que la variable cambia a 42 antes de que se compruebe
	 * que la condicion es falsa
	 *
	 * La diferencia es que el do-while permite ejecutar el bloque de codigo al menos una vez porque la condicion
	 * se evalua al final, mientras que como en el while se evalua la condicion al inicio, el bloque nunca se ejecuta
	 */

	//Ejercicio 1.8

//		uint8_t input = 2;
//		uint8_t output = 0;
//
//		switch(input){
//
//			case 0:
//				output = 10;
//				break;
//
//			case 1:
//				output = 20;
//				break;
//
//			case 2:
//				output = 30;
//				break;
//
//			case 3:
//				output = 40;
//				break;
//
//			default: // se ejecuta si ningun caso coincide
//				output = 99;
//				break;
//		}
//
	// se esperan los siguientes casos:
	//   - con input=0 el output sea 10
	//   - con input=1 el output sea 20
	//   - con input=3 el output sea 40
	//   - con input=7 el output sea 99


	//Ahora eliminando el break

//		uint8_t input = 1;
//		uint8_t output = 0;
//
//		switch(input){
//
//			case 0:
//				output = 10;
//				break;
//
//			case 1:
//				output = 20;
//
//			case 2:
//				output = 30;
//				break;
//
//			case 3:
//				output = 40;
//				break;
//
//			default:
//				output = 99;
//				break;
//		}

	// Se epera que con input=1 se entre al case 1 y el output
	// sea 20, pero como no hay break, siga al siguiente caso y el
	// output ahora sea 30

	/*
	 * Al eliminar intencionalmente el break, el programa continua ejecutando y pasa al siguiente caso aunque
	 * la condicion original ya haya coincidido yes a esto a lo que se le conoce como fall-through
	 */


    /* Loop forever */
	while(1){

	}
	return 0;
}

